/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pergunta.h"

int *
pergunta_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 7;

	return &result;
}
