/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PERGUNTA_H_RPCGEN
#define _PERGUNTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PERGUNTA_PROG 0x23451111
#define PERGUNTA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define pergunta 1
extern  int * pergunta_1(void *, CLIENT *);
extern  int * pergunta_1_svc(void *, struct svc_req *);
extern int pergunta_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pergunta 1
extern  int * pergunta_1();
extern  int * pergunta_1_svc();
extern int pergunta_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PERGUNTA_H_RPCGEN */
