/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operacao.h"

resultado *
operation_1_svc(partes *argp, struct svc_req *rqstp)
{
	static resultado  result;

	printf("O tipo de operação é: %c", argp->tipo);

	int p1 = argp->parte1.n1 * argp->parte2.n1;
	int p2 = argp->parte1.n2 * argp->parte2.n2;
	float v = argp->peso1 * p1 + argp->peso2 * p2;
	result.retorno = argp->peso3 * v;

	if (argp->tipo == 'a' && result.retorno > 7)
		result.status = 1;
	else
		result.status = 2;

	return &result;
}
