/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERACAO_H_RPCGEN
#define _OPERACAO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numeros {
	int n1;
	int n2;
};
typedef struct numeros numeros;

struct partes {
	struct numeros parte1;
	struct numeros parte2;
	int peso1;
	float peso2;
	double peso3;
	char tipo;
};
typedef struct partes partes;

struct resultado {
	int status;
	double retorno;
};
typedef struct resultado resultado;

#define SOMA_PROG 0x23451111
#define SOMA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPERATION 1
extern  resultado * operation_1(partes *, CLIENT *);
extern  resultado * operation_1_svc(partes *, struct svc_req *);
extern int soma_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPERATION 1
extern  resultado * operation_1();
extern  resultado * operation_1_svc();
extern int soma_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numeros (XDR *, numeros*);
extern  bool_t xdr_partes (XDR *, partes*);
extern  bool_t xdr_resultado (XDR *, resultado*);

#else /* K&R C */
extern bool_t xdr_numeros ();
extern bool_t xdr_partes ();
extern bool_t xdr_resultado ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERACAO_H_RPCGEN */
