/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quadrado.h"

int *
quadrado_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Valor recebido: %d\n", *argp);

	result = *argp * *argp;

	return &result;
}
