/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUADRADO_H_RPCGEN
#define _QUADRADO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define QUADRADO_PROG 0x23451111
#define QUADRADO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUADRADO 1
extern  int * quadrado_1(int *, CLIENT *);
extern  int * quadrado_1_svc(int *, struct svc_req *);
extern int quadrado_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUADRADO 1
extern  int * quadrado_1();
extern  int * quadrado_1_svc();
extern int quadrado_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUADRADO_H_RPCGEN */
