/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"

int *
soma_1_svc(numeros *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->n1 + argp->n2;

	return &result;
}
